version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"  # Celery connection
      - "15672:15672"  # Management UI

  celery:
    build: .
    command: celery -A your_django_app_name worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis

  celery_beat:
    build: .
    command: celery -A your_django_app_name beat --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis

volumes:
  postgres_data:
  redis_data: