# Generated by Django 5.2.4 on 2025-08-03 22:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Format: DD/MM/YYYY. Must be at least 13 years old.', null=True, validators=[accounts.models.validate_date_of_birth]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email will be automatically converted to lowercase.', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
