# Generated by Django 5.2.4 on 2025-08-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='old_slug',
            field=models.SlugField(blank=True, default='', help_text='Legacy slug field (can be ignored)', max_length=200),
        ),
    ]
