# Generated by Django 5.2.4 on 2025-08-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_category_slug_idx_product_product_slug_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Additional Image')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured image for this product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_featured', 'created_at'],
            },
        ),
    ]
